create table contracts
(
    id                     int8 generated by default as identity,
    number_of_contract     int4 not null,
    agreement_date         date,
    updated_agreement_date date,
    primary key (id)
);

insert into contracts
values (1, 1, '18-02-2020', '18-02-2020');
insert into contracts
values (2, 2, '01-11-2021', '17-11-2020');
insert into contracts
values (3, 3, '16-10-2020', '16-02-2021');
insert into contracts
values (4, 4, '01-01-2021', '15-02-2021');
